### ISSUE TITLE
[CLOSED] java.lang.RuntimeException: Project must have a state. 

### ISSUE THREAD

**Issue by n0rad** [n0rad/visuwall#1]
<a href="https://github.com/jsmadja"><img src="https://avatars.githubusercontent.com/u/356003?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jsmadja](https://github.com/jsmadja)**
_Friday May 06, 2011 at 09:56 GMT_
_Originally opened as https://github.com/awired/visuwall/issues/1_

---

11:52:31.378 [25448688@qtp-10378355-68] ERROR org.mortbay.log - /wall/orange-vallee/status
java.lang.RuntimeException: Project must have a state.
    at net.awired.visuwall.core.service.ProjectService.getState(ProjectService.java:152) ~[visuwall.war:0.0.1-SNAPSHOT]
    at net.awired.visuwall.core.service.WallHolderService.getStatus(WallHolderService.java:169) ~[visuwall.war:0.0.1-SNAPSHOT]
    at net.awired.visuwall.server.web.controller.WallController.getStatus(WallController.java:71) ~[classes/:na]
    at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_24]
    at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_24]
    at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:176) ~[visuwall.war:3.0.5.RELEASE]
    at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:426) ~[visuwall.war:3.0.5.RELEASE]
    at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:414) ~[visuwall.war:3.0.5.RELEASE]
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:790) ~[visuwall.war:3.0.5.RELEASE]
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:719) ~[visuwall.war:3.0.5.RELEASE]
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:644) ~[visuwall.war:3.0.5.RELEASE]
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:549) ~[visuwall.war:3.0.5.RELEASE]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) ~[visuwall.war:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820) ~[visuwall.war:na]
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511) ~[visuwall.war:6.1.26]
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:401) ~[visuwall.war:6.1.26]
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216) [visuwall.war:6.1.26]
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182) [visuwall.war:6.1.26]
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766) [visuwall.war:6.1.26]
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450) [visuwall.war:6.1.26]
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152) [visuwall.war:6.1.26]
    at org.mortbay.jetty.Server.handle(Server.java:326) [visuwall.war:6.1.26]
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542) [visuwall.war:6.1.26]
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928) [visuwall.war:6.1.26]
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549) [visuwall.war:6.1.26]
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212) [visuwall.war:6.1.26]
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404) [visuwall.war:6.1.26]
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228) [visuwall.war:6.1.26]
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582) [visuwall.war:6.1.26]

**Comment by n0rad** [comment]
<a href="https://github.com/n0rad"><img src="https://avatars.githubusercontent.com/u/541709?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [n0rad](https://github.com/n0rad)**
_Saturday May 28, 2011 at 20:37 GMT_

---

it happen when a project is removed or renamed in ci and can not be found when updateStatus

resolved
